# Generated by Django 4.1.3 on 2022-11-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=200)),
                ('initial_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=150)),
                ('prarent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminology.glossary')),
            ],
        ),
    ]
