# Generated by Django 4.1.3 on 2022-11-15 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("terminology", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glossary",
            name="initial_date",
        ),
        migrations.RemoveField(
            model_name="glossary",
            name="version",
        ),
        migrations.CreateModel(
            name="GlossaryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=200)),
                ("initial_date", models.DateField()),
                (
                    "glossary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="terminology.glossary",
                    ),
                ),
            ],
        ),
    ]
