# Generated by Django 4.1.3 on 2022-11-15 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "terminology",
            "0002_remove_glossary_initial_date_remove_glossary_version_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="glossaryversion",
            name="glossary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="terminology.glossary",
            ),
        ),
    ]
